# Generated by Django 5.1.7 on 2025-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_travelrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
