# Generated by Django 5.1.7 on 2025-03-20 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_travelrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
